pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLAG_DISABLE_EX_FOCUS : i32 = 0x200000EB;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLAG_EX_FOCUS : i32 = 0x200000EC;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLAG_EX_FLASH : i32 = 0x200000ED;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLAG_SEC_SEN_STATE : i32 = 0x200000EE;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLAG_SECRET_SENSATION : i32 = 0x200000EF;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLAG_SEC_SEN_CAMERA : i32 = 0x200000F0;

pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_RYU_X : i32 = 0x4F;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_RYU_Y : i32 = 0x50;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_TARGET_X : i32 = 0x51;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_TARGET_Y : i32 = 0x52;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_DISABLE_EX_FOCUS_TIMER : i32 = 0x53;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_SEC_SEN_TIMER : i32 = 0x54;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_OPPONENT_DIREC : i32 = 0x55;
pub const FIGHTER_RYU_INSTANCE_WORK_ID_FLOAT_VERT_EXTRA : i32 = 0x56;

pub const FIGHTER_RYU_INSTANCE_WORK_ID_INT_FLASH_TIMER : i32 = 0x100000C9;
