pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ENTER : i32 = 0;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_WAIT : i32 = 1;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SQUAT : i32 = 2;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SQUAT_WAIT : i32 = 3;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SQUAT_RV : i32 = 4;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_EXIT : i32 = 5;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_DASH_F : i32 = 6;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_DASH_B : i32 = 7;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK : i32 = 8;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_LW3 : i32 = 9;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_LW4 : i32 = 10;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_HI3 : i32 = 11;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_F3 : i32 = 12;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_B3 : i32 = 12;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SPECIAL_S : i32 = 14;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SPECIAL_S_DASH : i32 = 15;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SPECIAL_S_END : i32 = 16;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SPECIAL_S2_START : i32 = 17;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SPECIAL_S2_LOOP : i32 = 18;
// pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SPECIAL_S2_END : i32 = 19;

pub const FIGHTER_MARTH_INSTANCE_WORK_ID_FLAG_IS_STANCE : i32 = 0x200000E1;
pub const FIGHTER_MARTH_INSTANCE_WORK_ID_FLAG_PARRY_XLU : i32 = 0x200000E2;
pub const FIGHTER_MARTH_INSTANCE_WORK_ID_FLAG_AIR_STANCE : i32 = 0x200000E3;

pub const FIGHTER_MARTH_INSTANCE_WORK_ID_INT_STANCE_CHANGE_LOCKOUT : i32 = 0x100000BF;

pub const FIGHTER_MARTH_STATUS_FLAG_DISABLE_STANCE_CHANGE : i32 = 0x21000015;

pub const FIGHTER_MARTH_STATUS_STANCE_ATTACK_3_FLAG_CHANGE_MOTION : i32 = 0x2100000C;
pub const FIGHTER_MARTH_STATUS_STANCE_ATTACK_F3_FLAG_HEAVY : i32 = 0x2100000D;

pub const FIGHTER_MARTH_STATUS_STANCE_SPECIAL_S_FLAG_FLASHING_BLADE : i32 = 0x2100000C;
pub const FIGHTER_MARTH_STATUS_STANCE_SPECIAL_S_FLAG_DASH : i32 = 0x2100000D;
pub const FIGHTER_MARTH_STATUS_STANCE_SPECIAL_S_FLAG_END : i32 = 0x2100000E;

pub const FIGHTER_MARTH_STATUS_STANCE_SPECIAL_S_FLOAT_ANGLE : i32 = 0x1000007;

pub const FIGHTER_MARTH_STATUS_STANCE_SPECIAL_S2_START_SITUAITON : i32 = 0x11000005;
pub const FIGHTER_MARTH_STATUS_STANCE_SPECIAL_S2_LOOP_COUNT : i32 = 0x11000006;
