pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ENTER : i32 = 0;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_WAIT : i32 = 1;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SQUAT : i32 = 2;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SQUAT_WAIT : i32 = 3;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_SQUAT_RV : i32 = 4;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_DASH_F : i32 = 5;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_DASH_B : i32 = 6;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_EXIT : i32 = 7;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK : i32 = 8;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_LW3 : i32 = 9;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_LW4 : i32 = 10;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK_HI3 : i32 = 11;

pub const FIGHTER_MARTH_INSTANCE_WORK_ID_FLAG_IS_STANCE : i32 = 0x200000E1;
pub const FIGHTER_MARTH_INSTANCE_WORK_ID_FLAG_PARRY_XLU : i32 = 0x200000E2;

pub const FIGHTER_MARTH_INSTANCE_WORK_ID_INT_STANCE_CHANGE_LOCKOUT : i32 = 0x100000BF;
