pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ENTER : i32 = 0;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_WAIT : i32 = 1;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_EXIT : i32 = 2;
pub const FIGHTER_MARTH_STATUS_KIND_SPECIAL_LW_ATTACK : i32 = 3;

pub const FIGHTER_MARTH_INSTANCE_WORK_ID_FLAG_IS_STANCE : i32 = 0x200000E1;

pub const FIGHTER_MARTH_INSTANCE_WORK_ID_INT_STANCE_CHANGE_LOCKOUT : i32 = 0x100000BF;

