pub mod common;
pub mod daisy;
pub mod samusd;
pub mod lucina;
pub mod littlemac;
pub mod gaogaen;
pub mod dedede;
pub mod lucas;
pub mod jack;
pub mod kirby;
pub mod cloud;
pub mod lucario;
pub mod bayonetta;
pub mod dolly;
pub mod shulk;
pub mod pikachu;
pub mod robot;
// pub mod snake;
pub mod palutena;
pub mod master;
pub mod ryu;
pub mod toonlink;
pub mod zelda;
pub mod buddy;
pub mod ridley;
pub mod koopajr;
pub mod gamewatch;
pub mod donkey;
pub mod richter;
pub mod eflame;
pub mod element;
pub mod elight;
pub mod falco;
pub mod purin;
pub mod ken;
pub mod metaknight;
pub mod ganon;
pub mod wario;
pub mod luigi;
pub mod reflet;
pub mod miiswordsman;
pub mod edge;
pub mod pickel;
pub mod pitb;
pub mod diddy;
pub mod sheik;
// pub mod tantan;
pub mod yoshi;
pub mod mario;
pub mod duckhunt;
pub mod kamui;
pub mod samus;
pub mod mariod;
pub mod pacman;
pub mod miifighter;
pub mod pit;
pub mod wolf;
pub mod gekkouga;
pub mod szerosuit;
pub mod demon;
pub mod chrom;
// pub mod captain;
pub mod trail;
pub mod fox;
pub mod koopa;
pub mod packun;
pub mod link;
pub mod murabito;
pub mod shizue;

pub fn install() {
    common::install();
    daisy::install();
    samusd::install();
    lucina::install();
    littlemac::install();
    gaogaen::install();
    dedede::install();
    lucas::install();
    jack::install();
    kirby::install();
    cloud::install();
    lucario::install();
    bayonetta::install();
    dolly::install();
    shulk::install();
    pikachu::install();
    robot::install();
    // snake::install();
    palutena::install();
    master::install();
    ryu::install();
    toonlink::install();
    zelda::install();
    buddy::install();
    ridley::install();
    koopajr::install();
    gamewatch::install();
    donkey::install();
    richter::install();
    eflame::install();
    elight::install();
    falco::install();
    purin::install();
    ken::install();
    metaknight::install();
    ganon::install();
    wario::install();
    luigi::install();
    reflet::install();
    miiswordsman::install();
    edge::install();
    pickel::install();
    pitb::install();
    diddy::install();
    sheik::install();
    // tantan::install();
    yoshi::install();
    mario::install();
    duckhunt::install();
    kamui::install();
    samus::install();
    mariod::install();
    pacman::install();
    miifighter::install();
    pit::install();
    wolf::install();
    gekkouga::install();
    szerosuit::install();
    demon::install();
    chrom::install();
    // captain::install();
    trail::install();
    fox::install();
    koopa::install();
    packun::install();
    link::install();
    murabito::install();
    shizue::install();
}