#![feature(concat_idents)]
#![feature(proc_macro_hygiene)]
#![feature(asm)]

mod vars;
mod function_hooks;
mod gameplay;
mod common_funcs;
mod table_const;
mod global_frames;
mod common_status;
mod agent_inits;
mod daisy;
mod samusd;
mod lucina;
mod littlemac;
mod gaogaen;
mod dedede;
mod lucas;
mod jack;
mod kirby;
mod cloud;
mod lucario;
mod bayonetta;
mod dolly;
mod shulk;
mod pikachu;
mod robot;
mod snake;
mod palutena;
mod master;
mod ryu;
mod toonlink;
mod zelda;
mod buddy;
mod ridley;
mod koopajr;
mod gamewatch;
mod donkey;
mod richter;
mod eflame;
mod elight;
mod falco;
mod purin;
mod ken;
mod metaknight;
mod ganon;
mod wario;
mod luigi;
mod reflet;
mod miiswordsman;
mod edge;
mod pickel;
mod pitb;
mod diddy;
mod sheik;
mod tantan;
mod yoshi;
mod mario;
mod duckhunt;
mod rockman;
mod kamui;
mod samus;
mod mariod;
mod pacman;
mod miifighter;
mod pit;
mod wolf;
mod gekkouga;
mod szerosuit;
mod demon;
mod chrom;
// mod captain;
mod trail;

#[skyline::main(name = "the_wubor_patch")]
pub fn main() {
    vars::install();
    function_hooks::install();
    global_frames::install();
    common_status::install();
    agent_inits::install();
    daisy::install();
    samusd::install();
    lucina::install();
    littlemac::install();
    gaogaen::install();
    dedede::install();
    lucas::install();
    jack::install();
    kirby::install();
    cloud::install();
    lucario::install();
    bayonetta::install();
    dolly::install();
    shulk::install();
    pikachu::install();
    robot::install();
    snake::install();
    palutena::install();
    master::install();
    ryu::install();
    toonlink::install();
    zelda::install();
    buddy::install();
    ridley::install();
    koopajr::install();
    gamewatch::install();
    donkey::install();
    richter::install();
    eflame::install();
    elight::install();
    falco::install();
    // brave::install();
    purin::install();
    // wiifit::install();
    ken::install();
    metaknight::install();
    ganon::install();
    wario::install();
    luigi::install();
    reflet::install();
    miiswordsman::install();
    edge::install();
    pickel::install();
    pitb::install();
    diddy::install();
    sheik::install();
    tantan::install();
    yoshi::install();
    mario::install();
    duckhunt::install();
    rockman::install();
    kamui::install();
    samus::install();
    mariod::install();
    pacman::install();
    miifighter::install();
    pit::install();
    wolf::install();
    gekkouga::install();
    szerosuit::install();
    demon::install();
    chrom::install();
    // captain::install();
    trail::install();
}