mod fighter;
mod belmont;
mod brave;
mod captain;
mod demon;
mod dolly;
mod eflame;
mod elight;
mod gamewatch;
mod ganon;
mod gaogaen;
mod ike;
mod jack;
mod kirby;
mod koopa;
mod lucario;
mod lucina;
mod luigi;
mod mariod;
// mod ness;
mod pickel;
mod reflet;
mod rockman;
mod shotos;
mod shulk;
mod sonic;
mod wario;

mod weapon;
mod belmont_cross;
mod blaster_bullet;
mod dolly_wave;
mod dolly_burst;
mod edge_flare1;
mod ike_sword;
mod inkling_rollerink;
mod koopa_breath;
mod mariod_drcapsule;
mod packun_poisonbreath;
mod ryu_shinkuhadoken;

pub fn install() {
    fighter::install();
    belmont::install();
    brave::install();
    captain::install();
    demon::install();
    dolly::install();
    eflame::install();
    elight::install();
    gamewatch::install();
    ganon::install();
    gaogaen::install();
    ike::install();
    jack::install();
    kirby::install();
    koopa::install();
    lucario::install();
    lucina::install();
    luigi::install();
    mariod::install();
    // ness::install();
    pickel::install();
    reflet::install();
    rockman::install();
    shotos::install();
    shulk::install();
    sonic::install();
    wario::install();

    weapon::install();
    belmont_cross::install();
    blaster_bullet::install();
    dolly_wave::install();
    dolly_burst::install();
    edge_flare1::install();
    ike_sword::install();
    inkling_rollerink::install();
    koopa_breath::install();
    mariod_drcapsule::install();
    packun_poisonbreath::install();
    ryu_shinkuhadoken::install();
}
