name: Create PR Release

on:
  pull_request:
    branches:
      - dev

jobs:
  package-pr:
    runs-on: ubuntu-24.04
    container:
      image: wuboyth/skyline-plugin-builder:latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Get Branch Name
        id: branch-name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Download ROMFS
        id: pr-romfs
        continue-on-error: true
        shell: bash
        run: curl -O https://github.com/WuBoytH/WuBor-Romfs/releases/download/${{needs.get-version.outputs.branch}}/romfs.zip
      - name: Download ROMFS (Backup)
        if: steps.pr-romfs.outcome == 'failure'
        shell: bash
        run: curl -O https://github.com/WuBoytH/WuBor-Romfs/releases/download/dev/romfs.zip
      - name: Build Release NRO (PR)
        run: |
          cd scripts && python3 build.py pr
        env:
          HOME: /root
      - name: Setup Build Directory (PR)
        shell: bash
        run: |
          cd scripts && python3 create_pr.py && cd ..
      - name: Upload Plugin Artifact (PR)
        uses: actions/upload-artifact@v7.0.0
        with:
          name: The_WuBor_Patch_PR
          path: build/
