name: Create Release

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Get Plugin Version
        id: plugin-version
        # You may pin to the exact commit or the version.
        # uses: dante-signal31/rust-app-version@752c1afc51739ac75b36157cdd20e7116d203980
        uses: dante-signal31/rust-app-version@v1.0.0
      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6
    outputs:
      version: ${{ steps.plugin-version.outputs.app_version }}
      branch: ${{ steps.branch-name.outputs.current_branch }}

  package-main:
    needs: get-version
    if: ${{ contains(needs.get-version.outputs.branch, 'dev') != true }}
    runs-on: ubuntu-20.04
    container:
      image: jugeeya/cargo-skyline:3.2.0-no-dkp
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.9'
      - uses: actions/checkout@v3.1.0
      - name: Download ROMFS
        # You may pin to the exact commit or the version.
        # uses: i3h/download-release-asset@6a9870c8f1c561f9e67550d6177c31c2b1c49fef
        uses: i3h/download-release-asset@v1.3.3
        with:
          # 
          owner: WuBoytH
          # 
          repo: WuBor-Romfs
          # 
          tag: ${{needs.get-version.outputs.branch}}
          # 
          file: romfs.zip
      - name: Build Release NRO (Main)
        run: |
          cargo skyline build --release --no-default-features
        env:
          HOME: /root
      - name: Create Release ZIP (Main)
        shell: bash
        run: |
          cd scripts && python3 create_main.py && cd ..
      - name: Upload Plugin Artifact (Main)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: The_WuBor_Patch
          path: The_WuBor_Patch.zip

  package-dev:
    needs: get-version
    if: ${{ contains(needs.get-version.outputs.branch, 'dev') }}
    runs-on: ubuntu-20.04
    container:
      image: jugeeya/cargo-skyline:3.2.0-no-dkp
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.9'
      - uses: actions/checkout@v3.1.0
      - name: Download ROMFS
        # You may pin to the exact commit or the version.
        # uses: i3h/download-release-asset@6a9870c8f1c561f9e67550d6177c31c2b1c49fef
        uses: i3h/download-release-asset@v1.3.3
        with:
          # 
          owner: WuBoytH
          # 
          repo: WuBor-Romfs
          # 
          tag: ${{needs.get-version.outputs.branch}}
          # 
          file: romfs.zip
      - name: Build Release NRO (Dev)
        run: |
          cargo skyline build --release --features dev
        env:
          HOME: /root
      - name: Create Release ZIP (Dev)
        shell: bash
        run: |
          cd scripts && python3 create_dev.py && cd ..
      - name: Upload Plugin Artifact (Dev)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: The_WuBor_Patch_Dev
          path: The_WuBor_Patch_Dev.zip

  upload-main:
    runs-on: ubuntu-20.04
    needs: [ package-main, get-version ]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3.0.0
      - name: Create Main Draft Release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.get-version.outputs.version}}
          name: ${{needs.get-version.outputs.version}}
          draft: true
          prerelease: false
          body: >
            Full release of the latest version. DO NOT PUBLISH UNTIL THIS BODY HAS BEEN UPDATED.
            [You can view the changelogs for a specific version here.](https://drive.google.com/drive/folders/1yjnSZ5ZIBclAStsjJV1ODlBnJ3FYUaoD?usp=sharing)
            [You can view all changes up to a specific version here.](https://drive.google.com/drive/folders/1zIqkVWlZWb56ar7UqRTECYUVuBfqW0v1?usp=sharing)
            
            ## Installation
            
            Remove the `ultimate/mods/The WuBor Patch` folder, if you have one already.
            Extract `The_WuBor_Patch.zip` to the root of the SD card. The plugin should be included in `ultimate/mods/The WuBor Patch/`
          files: >
            The_WuBor_Patch/*
  upload-dev:
    runs-on: ubuntu-20.04
    needs: [ package-dev, get-version ]
    steps:
      # - name: Delete Version Dev Build
      #   uses: dev-drprasad/delete-tag-and-release@v0.2.0
      #   with:
      #     delete_release: true
      #     tag_name: ${{needs.get-version.outputs.version}}-dev
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download all artifacts
        uses: actions/download-artifact@v3.0.0
      - name: Create Dev Prerelease
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.get-version.outputs.version}}-dev
          name: ${{needs.get-version.outputs.version}}-dev
          draft: false
          prerelease: true
          body: >
            Nightly built off of ${{needs.get-version.outputs.version}}-dev/${{github.sha}}.
            [You can view the changelogs for a specific version here.](https://drive.google.com/drive/folders/1yjnSZ5ZIBclAStsjJV1ODlBnJ3FYUaoD?usp=sharing)
            These will be updated to match the most recent dev build (this one!).
            
            ## Installation
            
            Remove the `ultimate/mods/The WuBor Patch` folder, if you have one already.
            Extract `The_WuBor_Patch_Dev.zip` to the root of the SD card. The plugin should be included in `ultimate/mods/The WuBor Patch/`
          files: >
            The_WuBor_Patch_Dev/*