name: Create PR Release

on: 
  pull_request:
    branches:
      - dev

jobs:
  package-pr:
    runs-on: ubuntu-latest
    container:
      image: jugeeya/cargo-skyline:3.2.0
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.9'
      - uses: actions/checkout@v3.1.0
      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Download ROMFS
        id: pr-romfs
        continue-on-error: true
        uses: i3h/download-release-asset@v1.3.2
        with:
          # 
          owner: WuBoytH
          # 
          repo: WuBor-Romfs
          # 
          tag: ${{ steps.branch-name.outputs.current_branch }}
          # 
          file: romfs.zip
      - name: Download ROMFS (Backup)
        if: steps.pr-romfs.outcome == 'failure'
        uses: i3h/download-release-asset@v1.3.2
        with:
          # 
          owner: WuBoytH
          # 
          repo: WuBor-Romfs
          # 
          tag: dev
          # 
          file: romfs.zip
      - name: Build Release NRO (PR)
        run: |
          PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin /root/.cargo/bin/cargo-skyline skyline build --release --features pr
        env:
          HOME: /root
      - name: Setup Build Directory (PR)
        shell: bash
        run: |
          cd scripts && python3 create_pr.py && cd ..
      - name: Upload Plugin Artifact (PR)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: The_WuBor_Patch_PR
          path: build/
