name: Create PR Release

on: 
  pull_request:
    branches:
      - dev

jobs:
  package-pr:
    runs-on: ubuntu-20.04
    container:
      image: hewdrawremix/hewdraw-builder:latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.9'
      - uses: actions/checkout@v4.1.4
      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.1
      - name: Download ROMFS
        id: pr-romfs
        continue-on-error: true
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'WuBoytH/WuBor-Romfs'
          version: 'tags/${{ steps.branch-name.outputs.current_branch }}'
          file: 'romfs.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download ROMFS (Backup)
        if: steps.pr-romfs.outcome == 'failure'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'WuBoytH/WuBor-Romfs'
          version: 'tags/dev'
          file: 'romfs.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release NRO (PR)
        run: |
          cargo skyline build --release --features pr
        env:
          HOME: /root
      - name: Setup Build Directory (PR)
        shell: bash
        run: |
          cd scripts && python3 create_pr.py && cd ..
      - name: Upload Plugin Artifact (PR)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: The_WuBor_Patch_PR
          path: build/