name: Create PR Build

on: 
  pull_request:
    branches:
      - dev

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Get Plugin Version
        id: plugin-version
        # You may pin to the exact commit or the version.
        # uses: dante-signal31/rust-app-version@752c1afc51739ac75b36157cdd20e7116d203980
        uses: dante-signal31/rust-app-version@v1.0.0
      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6
    outputs:
      version: ${{ steps.plugin-version.outputs.app_version }}
      branch: ${{ steps.branch-name.outputs.current_branch }}

  package-pr:
    needs: get-version
    runs-on: ubuntu-latest
    container:
      image: jugeeya/cargo-skyline:3.0.0-dkp-beta
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2.4.2
      - name: Download ROMFS
        id: pr-romfs
        continue-on-error: true
        # You may pin to the exact commit or the version.
        # uses: i3h/download-release-asset@6a9870c8f1c561f9e67550d6177c31c2b1c49fef
        uses: i3h/download-release-asset@v1.3.2
        with:
          # 
          owner: WuBoytH
          # 
          repo: WuBor-Romfs
          # 
          tag: ${{needs.get-version.outputs.branch}}
          # 
          file: romfs.zip
      - name: Download ROMFS (Backup)
        if: steps.pr-romfs.outcome == 'failure'
        # You may pin to the exact commit or the version.
        # uses: i3h/download-release-asset@6a9870c8f1c561f9e67550d6177c31c2b1c49fef
        uses: i3h/download-release-asset@v1.3.2
        with:
          # 
          owner: WuBoytH
          # 
          repo: WuBor-Romfs
          # 
          tag: dev
          # 
          file: romfs.zip
      - name: Build Release NRO (PR)
        run: |
          PATH=$PATH:/root/.cargo/bin:/opt/devkitpro/devkitA64/bin /root/.cargo/bin/cargo-skyline skyline build --release --features pr
        env:
          HOME: /root
      - name: Create Release ZIP (PR)
        shell: bash
        run: |
          cd scripts && python3 create_pr.py && cd ..
      - name: Upload Plugin Artifact (PR)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: The_WuBor_Patch_PR.zip
