name: Create PR Release

on: 
  pull_request:
    branches:
      - dev

jobs:
  package-pr:
    runs-on: ubuntu-24.04
    container:
      image: wuboyth/skyline-plugin-builder:latest
    steps:
      - uses: actions/checkout@v4.1.4
      - name: Get Branch Name
        id: branch-name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Download ROMFS
        id: pr-romfs
        continue-on-error: true
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'WuBoytH/WuBor-Romfs'
          version: 'tags/${{ steps.branch-name.outputs.branch }}'
          file: 'romfs.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download ROMFS (Backup)
        if: steps.pr-romfs.outcome == 'failure'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'WuBoytH/WuBor-Romfs'
          version: 'tags/dev'
          file: 'romfs.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release NRO (PR)
        run: |
          cd scripts && python3 build.py pr
        env:
          HOME: /root
      - name: Setup Build Directory (PR)
        shell: bash
        run: |
          cd scripts && python3 create_pr.py && cd ..
      - name: Upload Plugin Artifact (PR)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: The_WuBor_Patch_PR
          path: build/