name: Comment PR artifacts links
on:
  workflow_run:
    workflows: ["Create PR Release"]
    types: [completed]
jobs:
  pr_comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Download all artifacts
        uses: actions/download-artifact@v3.0.0
      - uses: izhangzhihao/delete-comment@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_user_name: github-actions[bot]
          issue_number: ${{ github.event.number }}
      - uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-branch: ${{ steps.branch-name.outputs.current_branch }}
          artifacts: |
            The_WuBor_Patch_PR.zip